### PR TITLE
Adds metrics for blacklab

### PR DESCRIPTION
**Pull request by eginez**
These commits gives us the ability to push metrics to different backends. I have setup both prometheus and cloudwatch

### CODE REVIEW

**Comment by eginez** [comment]
Hey @severian what do you think about these changes to blacklab?

**Review by severian — APPROVED** [review]
This looks great to me!

**Comment by eginez** [comment]
awesome. I'll work on other changes needed to push this through

**Comment by eginez** [comment]
Hey @severian I think I have this in a good place now

The changes on this PR accomplish the following
- Introduces a dependency on `micrometer` to enable pushing metrics to different services
- Utilizes micrometer to register 2 metric services
   - Prometheus: enabled by default
   - Cloudwatch: enabled when running on an ec2 instance
     - Overrides the default cloudwatch client to enable us to push some basic dimensions we are interested in, namely: `Application`, `Environment` and `ContainerId`. 
     - It creates the `Application` metrics namespace.
 - Report basic jvm health metrics
 - Creates a handler for the prometheus `metrics` endpoint
 - Changes to log4j xml conf to silence netty's verbose output.
 - Metric publishing handled via a JVM property for easy disabling if need be

Some sample metrics I captured can be seen [here](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2:graph=~(view~'timeSeries~stacked~false~region~'us-west-2~metrics~(~(~'Application~'jvm.gc.pause.sum~'ContainerId~'b15fcada2e74~'InstanceId~'i-0909bcbdb51156233~'action~'end*20of*20minor*20GC~'cause~'Metadata*20GC*20Threshold~'Environment~'Unknown~'Application~'Blacklab)~(~'.~'jvm.gc.pause.count~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.avg~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.max~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.sum~'.~'.~'.~'.~'.~'.~'.~'G1*20Evacuation*20Pause~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.count~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.avg~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)~(~'.~'jvm.gc.pause.max~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.~'.)));query=~'*7bApplication*2cApplication*2cContainerId*2cEnvironment*2cInstanceId*2caction*2ccause*7d*20gc)

**Comment by severian** [comment]
@eginez sorry I somehow missed or didn't get a notification for this thread. At a glance all these further changes make sense to me. Seeing those gc metrics in CloudWatch is great.

**Pull request merged**
